### ISSUE TITLE
Crashes on clicking Queries

### ISSUE THREAD

**Issue by nchouard** [apollographql/apollo-client-devtools#119]
[Dev](url) tools is crashing whenever I click on Queries. Similar to what is happening in #107 

Mac OS 10.13.3
Chrome 66.0.3359.139
![screen shot 2018-05-15 at 5 56 22 pm](https://user-images.githubusercontent.com/31971995/40087729-8b7171c2-5869-11e8-8991-8fedec99c057.png)

**Comment by Negan1911** [comment]
Same here, i inspected the frame and was able to get this:
![image](https://user-images.githubusercontent.com/3399236/40093433-98ad0340-5898-11e8-8fa6-99794e7c147c.png)

**Comment by zebulonj** [comment]
Same here. My suspicion is that this is because my queries are anonymous (example below), but I haven't had a chance to verify yet.

```
query ( $slug: ID! ) {
  page( slug: $slug ) {
    id
    slug
    name
    ...
  }
}
```
vs.
```
query PageQuery ( $slug: ID! ) {
  page( slug: $slug ) {
    id
    slug
    name
    ...
  }
}
```

**Comment by zebulonj** [comment]
Nope. Named all my queries and mutations, and it still crashes anytime I attempt to open the Queries tab.

**Comment by andrewtpoe** [comment]
Same here.

macOS 10.13.4

Chrome 66.0.3359.181

**Comment by levindixon** [comment]
Same for me, started to debug the issue and it looks like `query.queryString` is always undefined here:
https://github.com/apollographql/apollo-client-devtools/blob/master/src/devtools/components/WatchedQueries/WatchedQueries.js#L15 hope that helps!

macOS: 10.13.4
Chrome:  66.0.3359.181
react-apollo: 2.1.4,
apollo-client: 2.3.1
apollo-link-state: 0.4.1

**Comment by pyromaniac** [comment]
Same here.

**Comment by umlx5h** [comment]
Same here.
Since query object of argument has no queryString property.
https://github.com/apollographql/apollo-client-devtools/blob/master/src/devtools/components/WatchedQueries/WatchedQueries.js#L15

This is properly working (react-apollo: 0.9.0)
![screen shot 2018-05-22 at 21 33 50](https://user-images.githubusercontent.com/20206121/40362866-c1e273a6-5e08-11e8-964d-c967e0b4fdb3.png)

This is not working (react-apollo: 2.1.4)
![screen shot 2018-05-22 at 21 37 13](https://user-images.githubusercontent.com/20206121/40362897-d741c030-5e08-11e8-95bf-f949e2415116.png)

to avoid crushes, add  `if (!query.queryString) return queryId;` line above WatchedQueries.js#L15
but this doen't fix the problem completely.

**Comment by Billy-** [comment]
@Negan1911 I am getting `cannot read property 'loc' of undefined` - seems to be related to that change?

**Comment by Negan1911** [comment]
@Billy- it could be, theres a chance that you have a bad mutation without body?

**Comment by Billy-** [comment]
@Negan1911 that is something I considered.. I did a scan of my code base and couldn't find any.. And it's impossible to debug :slightly_frowning_face:. My app works fine - would I expect any errors in the app if a mutation had no body?

**Comment by kmontag** [comment]
In case anyone finds this useful: I was running into the `cannot read property 'loc' of undefined` error, and fixed it by changing a query like this:

```
query MyQuery($id) {
  model(id: $id) {
    association {
      // ... association fields
    }
  }
}
```

to this:

```
query MyQuery($id) {
  model(id: $id) {
    // Request a field on the root object
    id

    association {
      // ... association fields
    }
  }
}
```
