### ISSUE TITLE
Impossible to track newly-created ApolloClients

### ISSUE THREAD

**Issue by vezaynk** [apollographql/apollo-client-devtools#1240]
In my application, the ApolloClient is disposed of, and a new one is created for every session.

Devtools only see the first one.

**Intended outcome:**

I should see all active ApolloClients

**Actual outcome:**

I only see the first ApolloClient

**How to reproduce the issue:**

To test make an event that makes a new client and calls a new query:

```ts
let client = new ApolloClient() // initial client, we can see this
function newClientNewQuery() {
   client.stop() // dispose of old client, is this the right way to do it?
   client = new ApolloClient() // How can I inspect this client?
   client.query(...) // How can I inspect this query?
}

setInterval(() => newClientNewQuery(), 20_000);
```

**Comment by jerelmiller** [comment]
Thanks for the report @vezaynk! We're wrapping up some changes to the devtools message passing to provide more stability and once we are done with this, we'll be looking at making multiple clients work nicer with each other.

Thanks for bringing this use case up! I think we might have missed this otherwise. Thank you!

**Comment by jerelmiller** [comment]
Hey @vezaynk 👋 

I was able to get a fix for this in https://github.com/apollographql/apollo-client-devtools/pull/1303. I'm hoping to get this out this week. Thanks again for the report!
