### ISSUE TITLE
Queries and Cache is empty with React App ans useMemo() for the client

### ISSUE THREAD

**Issue by pitgrap** [apollographql/apollo-client-devtools#298]
We're developing an React app mit Apollo. For performance reasons we're keeping the client with React Hook useMemo(). But then we see no queries and cache in the devTools. If we remove useMemo(), the dev tools are working again.

Used Versions:
- "@apollo/client": "^3.1.3",
- "react": "^16.13.1",
- DevTools: 2.3.1 with Firefox 83 Developer Edition, Windows 10

Example Code to reproduce it:

```
const App: React.FC = () => {
  
  const client = useMemo(() => {
    return new ApolloClient({
      cache: new InMemoryCache({
        possibleTypes,
      }),
      link: new HttpLink({
        uri: ...,
      }),
    });
  }, []);

  return (
    <ApolloProvider client={client}>
      ...
    </ApolloProvider>
  );
};
```

**Comment by hwillson** [comment]
@pitgrap Is this still a problem with version 3 of the devtools?

**Comment by pitgrap** [comment]
Hi @hwillson, sorry I can't tell you, because now we're using the Apollo client with a single instance without `useMemo()`.

**Comment by hwillson** [comment]
Thanks @pitgrap - I’ll close this off for now. If anyone is still encountering this issue with AC Devtools >= 3, let us know.

**Comment by elGatoMantocko** [comment]
In my app, I noticed we had this problem. Whether or not the devtools sees the queries/cache seems _really_ inconsistent but I'm not really sure why.

In my hook, I just added a check to delete the `__APOLLO_CLIENT__` from the window in each execution of my memo and that seems to work for me.

```ts
const apolloClient = useMemo(() => {
  if ('__APOLLO_CLIENT__' in window) {
    delete window.__APOLLO_CLIENT__;
  }
  return new ApolloClient({ connectToDevtools: true });
}, [myStuff])
```

Using devtools version 4.1.4 with apollo client 3.7.10.

**Comment by phryneas** [comment]
In React 18, `useMemo` will execute twice, so you create two Apollo clients to register with the Devtools.

The first client registers with the devtools, the second client will be kept to use by React.

Generally, `useMemo` is the wrong place to keep the Apollo Client, as React keeps the right to discard that at will in the future - [from the docs](https://reactjs.org/docs/hooks-faq.html#how-to-memoize-calculations):

> You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance. (For rare cases when a value must never be recomputed, you can [lazily initialize](https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily) a ref.)

The idiomatic solution would be to move the client out of the component like

```ts
const client = new ApolloClient({
  cache: new InMemoryCache({
    possibleTypes,
  }),
  link: new HttpLink({
    // uri: ...,
  }),
});

const App: React.FC = () => {
  return <ApolloProvider client={client}>...</ApolloProvider>;
};
```

If that is not possible, you could think about using `useState`, which has a stronger guarantee to be kept, as it is handled as "state", not as an optimization like `useMemo` would be, with a state initializer function, but that _will also execute twice in StrictMode_.

```js
// will also execute `createClient` twice, but at least not get thrown away
const [client] = useState(createClient);
```

The alternative to that would be a ref, which is also more "state" than "optimization". While generally, a ref should not be read or written during render, writing to it is [fine for initialization](https://beta.reactjs.org/reference/react/useRef#avoiding-recreating-the-ref-contents), and since the ref contents will never change, reading it should be fine as well:

```ts
const App: React.FC = () => {
  const clientRef = useRef(null);
  if (clientRef.current === null) {
    clientRef.current = new ApolloClient({
      cache: new InMemoryCache({
        possibleTypes,
      }),
      link: new HttpLink({
        // uri: ...,
      }),
    });
  }
  const client = clientRef.current;

  return <ApolloProvider client={client}>...</ApolloProvider>;
};
```
