### ISSUE TITLE
Variables don't copy to graphQL playground tab on 'run in GraphQL' click

### ISSUE THREAD

**Issue by HGZdev** [apollographql/apollo-client-devtools#458]
**Intended outcome:**
Clicking in 'Run in GraphQL' button copy query and variables to playground console.

**Actual outcome:**
Variables window remains empty.

**How to reproduce the issue:**
Select query/mutation => click 'Run in GraphQL' button

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser chrome
 - Browser version 89.0.4389.82
 - Extension version 3.0.0

**Comment by danielb7390** [comment]
Having the same problem.
Actually there's no variables shown in the queries history for me, and so clicking in "Run in GraphQL"  can't copy the non existing variables.

OS: Windows 10
Browser chrome
Browser version 89.0.4389.82
Extension version 3.0.0

**Comment by bmviniciuss** [comment]
Having the same problem.

OS: Ubuntu 20.04
Browser: Brave
Version 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)

**Comment by michaelFrancisco** [comment]
I have the same issue, using a Vue.js app with apollo-client@2.6.10

![image](https://user-images.githubusercontent.com/54756557/111240535-63768600-8636-11eb-8dc2-e96f4a2f8cbf.png)

Apollo devtools used to work fine before the recent update

OS: Ubuntu 20.04
Browser: Chrome
Version: 88.0.4324.150 (Official Build) (64-bit)
Extension version: 3.0.1

**Comment by bmviniciuss** [comment]
I've tried to fix the problem by creating a `graphiQLQueryVariables` var and re-passing to the `GraphiQL` component. On the `Mutations` the `mutation` variables are passed to the `RunInGraphQLButton` and set onClick.
```typescript
export const graphiQLQueryVariables = makeVar<any>(undefined);

 const query = useReactiveVar(graphiQLQuery);
 const queryVariables = useReactiveVar(graphiQLQueryVariables)

<GraphiQL
        ref={graphiQLRef}
        fetcher={(args) => executeOperation(args)}
        schema={schema}
        query={query}
        variables={queryVariables ? JSON.stringify(queryVariables, null,2) : ""}
....
```
```typescript
 onClick={() => {
      graphiQLQuery(operation);
      graphiQLQueryVariables(variables)
      currentScreen(Screens.Explorer);
    }}
```

This makes the variables appear on the Explorer, but i don't know if this is the best solution to this problem. But i got stuck on another problem. On `main` if a re-run a mutation (even if i type the variables), i'm getting a Parse Error on the Mutations Tab. And it's caused because the second mutation on the list does have the `source`/`mutationString`  as `undefined`.
 
![image](https://user-images.githubusercontent.com/20448523/111249283-3b613580-85ea-11eb-816a-33a4dd86de0c.png)
![image](https://user-images.githubusercontent.com/20448523/111249296-4025e980-85ea-11eb-80c0-5dc71011ada9.png)

**Comment by bmschwartz** [comment]
This is incredibly frustrating because hitting "Run in GraphiQL" to get the query/mutation with identical variables was the most useful feature in this extension. Wish I could downgrade until this is fixed.

**Comment by bmviniciuss** [comment]
@bmschwartz you could clone the repo on the tag before the 3.0 version and build the extesion from there and install manually on the browser.

**Comment by bmschwartz** [comment]
> @bmschwartz you could clone the repo on the tag before the 3.0 version and build the extesion from there and install manually on the browser.

Thanks, I'll do that!

**Comment by max-humu** [comment]
+1 on "Run in GraphiQL" with identical variables being one of the most useful features of this extension. This seems like a fairly major regression that has impacted my workflow. It would be great if this could receive some attention soon. That said, thanks for everyone's amazing work on this extension thus far! The fact that so many people notice this just goes to show what a large impact this extension has.

**Comment by hwillson** [comment]
Hi all - definitely a regression; we're working on a fix. Thanks and sorry about the headache!
