### ISSUE TITLE
Firefox: "This add-on could not be installed because it appears to be corrupt"

### ISSUE THREAD

**Issue by dlbnco** [apollographql/apollo-client-devtools#528]
**Intended outcome:**

I tried to build and install it manually since it's not released yet. 

**Actual outcome:**

<img width="451" alt="image" src="https://user-images.githubusercontent.com/16964673/115591764-d82d8780-a2a8-11eb-849f-069677223ac6.png">

Note: It works when loaded as a temporary addon — `about:debugging#/runtime/this-firefox` → "Load Temporary Add-on":

<img width="699" alt="image" src="https://user-images.githubusercontent.com/16964673/115593820-5f7bfa80-a2ab-11eb-9572-f2cdc8cd74d8.png">

**How to reproduce the issue:**

1. `npm install`
2. `npm build:prod`
3. `npm zip:firefox`
4. In `about:addons`, select ⚙️ → "Install Add-on From File..."

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.3
 - Browser Firefox Developer Edition
 - Browser version 89.0b1 (64-bit)
 - Extension version 3.0.4

**Comment by hwillson** [comment]
Thanks @dlbnco - this is a known limitation. When you generate and try to install the add-on locally, it isn't signed. Because of this Firefox won't let you install it without using the "Load Temporary Add-on" method. I'll update the `README` to mention this.

On a related note, devtools 3.0.5 is currently in review with Firefox, and will hopefully be in their store shortly. Thanks!
