### ISSUE TITLE
Active Queries never go away

### ISSUE THREAD

**Issue by kaysond** [apollographql/apollo-client-devtools#815]
**Intended outcome:**
Active Queries should not multiply when the component is re-rendered

**Actual outcome:**
Every time a component that uses `useQuery()` is unmounted and re-rendered, the query is appended to the list of "Active Queries"
![image](https://user-images.githubusercontent.com/1147328/155203244-62d67d06-225b-4e9b-b4f4-92e3ea2a44f9.png)

**How to reproduce the issue:**
I posted some more context/questions on the forums here: https://community.apollographql.com/t/im-new-to-apollo-ive-built-a-functional-app-server-client-and-now-i-have-a-few-questions-about-queries-caching-and-dev-tools/2793/2
It's entirely possible that this is user error, but as I've not received any responses on the forums, I'm creating an issue here as well in case it is in fact an extension issue.

If it's not an obvious bug or obvious user error, I can try to create a minimal repro.

The gist of it is that I have conditionally rendered components (like modals) using `useQuery()`. If I render that component, it adds a query to "Active Queries". If I destroy the component, the Active Query stays there. The same thing happens if I change the props to the component (which changes the variable passed to the query).

I don't have a massive memory leak, so I don't expect that the queries are all actually sitting there, active, but it makes the extension very difficult to use.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (happens with Chrome too)
 - Browser version: 91.6.0esr
 - Extension version: 4.0.0

**Comment by dc-p8** [comment]
Queries made via apolloClient.query() are not shown in the devtool. But request made via watchQuery are. Also the extension GraphQL Network correctly show the requests made via query().

**Comment by jerelmiller** [comment]
@dc-p8 unfortunately this is a known limitation of the current extension implementation (https://github.com/apollographql/apollo-client-devtools/issues/588). I've got some ideas on how to approach this to provide one-off queries in the devtools in an intuitive way, but we've not prioritized it quite yet. I'm hoping we can look at this soon 🙂.

If you have any additional comments, I'd suggest putting it in #588 since that is more geared toward the issue you're talking about.

---

@kaysond thanks for your patience on this issue. I'm curious, do you still see this issue in recent versions of the devtools? I believe this issue may have been fixed, but would love to make sure before I close this.

**Comment by kaysond** [comment]
It's been a long time since I've looked at this sorry.

**Comment by jerelmiller** [comment]
Its ok! I haven't seen this surface in quite some time so I'm going to assume its been solved at this point. I'd be happy to reopen if we get more reports of this happening. Have a great day!
