### ISSUE TITLE
Integration with React Native

### ISSUE THREAD

**Issue by glauberfc** [apollographql/apollo-client-devtools#95]
There is any way to integrate Apollo client devtools with React Native?

**Comment by leomeloxp** [comment]
Hi @glauberfc if you haven't yet, have a look at #6 or possibly the related issue for [React Native Debugger](https://github.com/jhen0409/react-native-debugger/issues/177).

Cheers 👍

**Comment by JonathonJulian** [comment]
Was really hoping to ditch redux for apollo-link-state for a new greenfield RN project, unfortunately no debugger support could be a show stopper seeing as I do get a pretty decent experience with Redux and React Native Debugger  :(

**Comment by karsens** [comment]
Hey guys. I've been building an app with React Native + Expo + Redux + Apollo 1.X since past november and it's getting buggy on the connection part sometimes. I really wanna move to Apollo 2, but no apollo debugger shows up. Is there  someone that got this to work? That would be of great help!

**Comment by Gongreg** [comment]
Hey, I see that the issue is still not closed.
Just notifying that integration for React Native was released at the beginning of the year, you can find details inside https://github.com/jhen0409/react-native-debugger/blob/master/docs/apollo-client-devtools-integration.md .

@hwillson, @peggyrayzis, would it be possible to notify community about React Native dev tools for Apollo? I feel like devtools is a big helper for people working with React Native to try out Apollo.

I've never saw a mention of it anywhere, just github issues.
Also this issue can be closed.

**Comment by glauberfc** [comment]
Thanks!

**Comment by mohit23x** [comment]
you can also checkout the [flipper plugin](https://github.com/razorpay/react-native-apollo-devtools) for react native
